apiVersion: apps/v1
kind: Deployment
metadata:
  name: ProductService-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ProductService
  template:
    metadata:
      labels:
        app: ProductService
    spec:
      containers:
      - name: ProductService
        image: vikas079/ProductService:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
